import type { Metadata } from 'next'
import { Julius_Sans_One } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import './globals.css'
import 'leaflet/dist/leaflet.css'
import { cookies, headers } from 'next/headers'
import { defaultLocale } from '@/lib/locales'
import { isDisableDark } from '@/lib/theme'

// Mark layout dynamic since we read cookies/headers for locale detection
export const dynamic = 'force-dynamic'

const juliusSansOne = Julius_Sans_One({
  variable: '--font-julius-sans-one',
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  preload: true,
})

const fallbackSiteUrl = 'http://localhost:3000'
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || fallbackSiteUrl
const siteMetadataBase = (() => {
  try {
    return new URL(siteUrl)
  } catch {
    return new URL(fallbackSiteUrl)
  }
})()

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  metadataBase: siteMetadataBase,
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
    url: siteMetadataBase.toString(),
    siteName: process.env.NEXT_PUBLIC_SITE_NAME || 'Hakuna Mataweb',
    locale: 'fr_FR',
    type: 'website',
    images: [
      {
        url: '/images/logo.png',
        width: 800,
        height: 600,
        alt: 'Site Logo',
      },
    ],
  },
}

import DevPerfProtector from '@/components/dev/DevPerfProtector'
import { SchemaOrg } from '@/components/seo/SchemaOrg'
import CookieConsentBanner from '@/components/shared/CookieConsentBanner'

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  let locale = defaultLocale
  let cookieConsent: 'accepted' | 'rejected' | undefined

  try {
    const cookieStore = await cookies()
    const cookieLocale = cookieStore.get('locale')?.value
    const consentValue = cookieStore.get('cookie_consent')?.value
    if (consentValue === 'accepted' || consentValue === 'rejected') {
      cookieConsent = consentValue
    }
    if (cookieLocale === 'fr' || cookieLocale === 'en') {
      locale = cookieLocale
    } else {
      locale = defaultLocale
    }
  } catch {
    // Fallback: parse header cookie string if cookies() is unavailable
    try {
      const cookieHeader = (await headers()).get('cookie') ?? ''
      const match = cookieHeader.match(/(?:^|; )locale=([^;]+)/)
      const parsedLocale = match ? decodeURIComponent(match[1]) : defaultLocale
      const consentMatch = cookieHeader.match(/(?:^|; )cookie_consent=([^;]+)/)
      const parsedConsent = consentMatch
        ? decodeURIComponent(consentMatch[1])
        : undefined
      if (parsedConsent === 'accepted' || parsedConsent === 'rejected') {
        cookieConsent = parsedConsent
      }
      locale =
        parsedLocale === 'fr' || parsedLocale === 'en'
          ? parsedLocale
          : defaultLocale
    } catch {
      locale = defaultLocale
    }
  }

  const disableDark = isDisableDark()

  const schemaCuisine = process.env.NEXT_PUBLIC_SCHEMA_CUISINE?.split(',')
    .map((item) => item.trim())
    .filter(Boolean)

  const schemaSameAs = process.env.NEXT_PUBLIC_SCHEMA_SAME_AS?.split(',')
    .map((item) => item.trim())
    .filter(Boolean)

  const hasAddress =
    process.env.NEXT_PUBLIC_SCHEMA_STREET_ADDRESS ||
    process.env.NEXT_PUBLIC_SCHEMA_CITY ||
    process.env.NEXT_PUBLIC_SCHEMA_POSTAL_CODE ||
    process.env.NEXT_PUBLIC_SCHEMA_COUNTRY

  const schemaAddress = hasAddress
    ? {
        streetAddress: process.env.NEXT_PUBLIC_SCHEMA_STREET_ADDRESS,
        addressLocality: process.env.NEXT_PUBLIC_SCHEMA_CITY,
        postalCode: process.env.NEXT_PUBLIC_SCHEMA_POSTAL_CODE,
        addressCountry: process.env.NEXT_PUBLIC_SCHEMA_COUNTRY,
      }
    : undefined

  let schemaOpeningHours:
    | Array<{
        dayOfWeek: string | string[]
        opens: string
        closes: string
      }>
    | undefined
  const openingHoursRaw = process.env.NEXT_PUBLIC_SCHEMA_OPENING_HOURS
  if (openingHoursRaw) {
    try {
      const parsed = JSON.parse(openingHoursRaw)
      if (Array.isArray(parsed)) {
        schemaOpeningHours = parsed
      }
    } catch {
      schemaOpeningHours = undefined
    }
  }

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={juliusSansOne.variable}
      data-disable-dark={disableDark ? 'true' : undefined}
    >
      <body className="font-sans antialiased">
        {/* Structured data for SEO */}
        <SchemaOrg
          type="Restaurant"
          name={process.env.NEXT_PUBLIC_SITE_NAME}
          description={process.env.NEXT_PUBLIC_SCHEMA_DESCRIPTION}
          url={process.env.NEXT_PUBLIC_SITE_URL}
          logo={process.env.NEXT_PUBLIC_SCHEMA_LOGO}
          telephone={process.env.NEXT_PUBLIC_SCHEMA_TELEPHONE}
          email={process.env.NEXT_PUBLIC_SCHEMA_EMAIL}
          address={schemaAddress}
          areaServed={process.env.NEXT_PUBLIC_SCHEMA_AREA_SERVED}
          priceRange={process.env.NEXT_PUBLIC_SCHEMA_PRICE_RANGE}
          servesCuisine={schemaCuisine}
          menu={process.env.NEXT_PUBLIC_SCHEMA_MENU}
          acceptsReservations={
            process.env.NEXT_PUBLIC_SCHEMA_ACCEPTS_RESERVATIONS
              ? process.env.NEXT_PUBLIC_SCHEMA_ACCEPTS_RESERVATIONS === 'true'
              : undefined
          }
          openingHours={schemaOpeningHours}
          geo={
            process.env.NEXT_PUBLIC_SCHEMA_LATITUDE &&
            process.env.NEXT_PUBLIC_SCHEMA_LONGITUDE
              ? {
                  latitude: Number(process.env.NEXT_PUBLIC_SCHEMA_LATITUDE),
                  longitude: Number(process.env.NEXT_PUBLIC_SCHEMA_LONGITUDE),
                }
              : undefined
          }
          sameAs={schemaSameAs}
        />
        {/* Dev-only protective wrapper to avoid dev tooling throwing on performance.measure */}
        <DevPerfProtector />
        {children}
        {!cookieConsent && <CookieConsentBanner />}
        {cookieConsent === 'accepted' && <Analytics />}
      </body>
    </html>
  )
}
